#include <string.h>
#include "esp_log.h"
#include "esp_timer.h"
#include "obu_core.h"
#include "obu_ipc.h"
#include "obu_radio.h"
static const char*TAG="c5_main";static obu_ipc_endpoint_t*ipc;static obu_radio_t*radio;static uint32_t ipc_seq;
typedef struct __attribute__((packed)){obu_v2x_rx_meta_t meta;uint16_t frame_len;}rx_wire_t;
typedef struct __attribute__((packed)){uint32_t request_id;uint16_t frame_len;uint16_t flags;}tx_req_t;
typedef struct __attribute__((packed)){uint32_t request_id;int32_t result;uint16_t frame_len;uint16_t reserved;}tx_res_t;
typedef struct __attribute__((packed)){uint16_t frequency_mhz;uint8_t enable;uint8_t reserved;}radio_cfg_t;
typedef struct __attribute__((packed)){uint32_t nonce;uint8_t arm;uint8_t reserved[3];}arm_t;
static void send_status(void){obu_radio_status_t s;obu_radio_get_status(radio,&s);s.ipc_drop=obu_ipc_rx_queue_drops(ipc)+obu_ipc_tx_queue_drops(ipc);obu_ipc_message_t m={.type=OBU_IPC_RADIO_STATUS,.sequence=ipc_seq++,.source_monotonic_us=obu_monotonic_us(),.payload_len=sizeof(s)};memcpy(m.payload,&s,sizeof(s));(void)obu_ipc_send(ipc,&m,0);}
static void on_rx(const obu_v2x_rx_meta_t*meta,const uint8_t*f,size_t n,void*ctx){(void)ctx;if(sizeof(rx_wire_t)+n>OBU_IPC_PAYLOAD_MAX){ESP_LOGW(TAG,"RX frame too large for IPC: %u",(unsigned)n);return;}obu_ipc_message_t m={.type=OBU_IPC_RX_FRAME,.sequence=ipc_seq++,.source_monotonic_us=meta->c5_rx_monotonic_us,.payload_len=(uint16_t)(sizeof(rx_wire_t)+n)};rx_wire_t w={.meta=*meta,.frame_len=(uint16_t)n};memcpy(m.payload,&w,sizeof(w));memcpy(m.payload+sizeof(w),f,n);(void)obu_ipc_send(ipc,&m,0);}
static void handle(const obu_ipc_message_t*m){if(m->type==OBU_IPC_SET_RADIO&&m->payload_len>=sizeof(radio_cfg_t)){radio_cfg_t c;memcpy(&c,m->payload,sizeof(c));if(c.enable)obu_radio_start(radio);obu_radio_set_frequency(radio,c.frequency_mhz);send_status();}else if(m->type==OBU_IPC_ARM_TX&&m->payload_len>=sizeof(arm_t)){arm_t a;memcpy(&a,m->payload,sizeof(a));esp_err_t e=obu_radio_arm_tx(radio,a.nonce,a.arm!=0);ESP_LOGW(TAG,"TX arm=%u result=%s",a.arm,esp_err_to_name(e));send_status();}else if(m->type==OBU_IPC_TX_REQUEST&&m->payload_len>=sizeof(tx_req_t)){tx_req_t q;memcpy(&q,m->payload,sizeof(q));esp_err_t e=ESP_ERR_INVALID_SIZE;if(sizeof(q)+q.frame_len<=m->payload_len)e=obu_radio_transmit(radio,m->payload+sizeof(q),q.frame_len);tx_res_t r={.request_id=q.request_id,.result=e,.frame_len=q.frame_len};obu_ipc_message_t o={.type=OBU_IPC_TX_RESULT,.sequence=ipc_seq++,.source_monotonic_us=obu_monotonic_us(),.payload_len=sizeof(r)};memcpy(o.payload,&r,sizeof(r));(void)obu_ipc_send(ipc,&o,0);}else if(m->type==OBU_IPC_TIME_PROBE&&m->payload_len>=8){uint64_t t1;memcpy(&t1,m->payload,8);uint64_t t2=obu_monotonic_us();obu_ipc_message_t o={.type=OBU_IPC_TIME_RESPONSE,.sequence=ipc_seq++,.source_monotonic_us=t2,.payload_len=24};memcpy(o.payload,&t1,8);memcpy(o.payload+8,&t2,8);uint64_t t3=obu_monotonic_us();memcpy(o.payload+16,&t3,8);(void)obu_ipc_send(ipc,&o,0);}}
void app_main(void){obu_ipc_config_t ic={.role=OBU_IPC_ROLE_C5_SLAVE,.host=SPI2_HOST,.gpio_sclk=8,.gpio_miso=9,.gpio_mosi=10,.gpio_cs=1,.gpio_data_ready=0,.queue_depth=12,.clock_hz=8000000};ESP_ERROR_CHECK(obu_ipc_init(&ic,&ipc));obu_radio_config_t rc={.frequency_mhz=5900,.rx_cb=on_rx};ESP_ERROR_CHECK(obu_radio_create(&rc,&radio));ESP_ERROR_CHECK(obu_radio_start(radio));send_status();uint64_t last=0;for(;;){obu_ipc_message_t m;if(obu_ipc_receive(ipc,&m,pdMS_TO_TICKS(250))==ESP_OK)handle(&m);uint64_t now=obu_monotonic_us();if(now-last>1000000){send_status();last=now;}}}
