#include "obu_gnss.h"
#include <ctype.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "esp_log.h"
#include "freertos/task.h"
struct obu_l76k{obu_l76k_config_t c;TaskHandle_t task;uint32_t seq;};
static const char *TAG = "obu_gnss";
static double dm(const char*s){double v=strtod(s,0);int deg=(int)(v/100.0);return deg+(v-deg*100.0)/60.0;}
static bool checksum_ok(const char*s){if(!s||*s!='$')return false;const char*star=strchr(s,'*');if(!star)return false;unsigned x=0;for(const char*p=s+1;p<star;p++)x^=(unsigned char)*p;return (unsigned)strtoul(star+1,0,16)==x;}
static int split(char*s,char**f,int max){int n=0;for(char*p=s;*p&&n<max;){f[n++]=p;char*c=strchr(p,',');if(!c)break;*c=0;p=c+1;}return n;}
static int64_t rmc_utc(const char*t,const char*d){if(!t||!d||strlen(t)<6||strlen(d)<6)return 0;struct tm x={0};x.tm_hour=(t[0]-'0')*10+t[1]-'0';x.tm_min=(t[2]-'0')*10+t[3]-'0';x.tm_sec=(t[4]-'0')*10+t[5]-'0';x.tm_mday=(d[0]-'0')*10+d[1]-'0';x.tm_mon=((d[2]-'0')*10+d[3]-'0')-1;int yy=(d[4]-'0')*10+d[5]-'0';x.tm_year=(yy>=80?yy:yy+100);char copy[64]={0};const char*old=getenv("TZ");if(old)strncpy(copy,old,sizeof(copy)-1);setenv("TZ","UTC0",1);tzset();time_t sec=mktime(&x);if(old)setenv("TZ",copy,1);else unsetenv("TZ");tzset();return (int64_t)sec*1000000000LL;}
static void pub_raw(struct obu_l76k*g,const char*line,uint64_t mono){obu_event_t e={.source=OBU_SOURCE_GNSS,.type=OBU_DATA_GNSS_NMEA,.sequence=g->seq++,.flags=OBU_EVENT_F_RAW|OBU_EVENT_F_VALID,.source_monotonic_us=mono,.validity_ms=2000};size_t n=strnlen(line,OBU_EVENT_PAYLOAD_MAX);e.payload_len=(uint16_t)n;memcpy(e.payload,line,n);obu_bus_publish(g->c.bus,&e);}
static void parse_and_pub(struct obu_l76k*g,char*line,uint64_t mono){if(!checksum_ok(line))return;char work[160];strncpy(work,line,sizeof(work)-1);work[sizeof(work)-1]=0;char*star=strchr(work,'*');if(star)*star=0;char*f[24];int n=split(work,f,24);if(n<1)return;obu_gnss_fix_t fix={0};bool emit=false;if((strstr(f[0],"RMC"))&&n>9){fix.utc_ns=rmc_utc(f[1],f[9]);fix.utc_valid=fix.utc_ns>0;if(f[2][0]=='A'&&f[3][0]&&f[5][0]){double lat=dm(f[3]),lon=dm(f[5]);if(f[4][0]=='S')lat=-lat;if(f[6][0]=='W')lon=-lon;fix.latitude_e7=(int32_t)llround(lat*1e7);fix.longitude_e7=(int32_t)llround(lon*1e7);fix.position_valid=true;fix.speed_mm_s=(uint32_t)llround(strtod(f[7],0)*0.514444*1000.0);fix.course_cdeg=(uint32_t)llround(strtod(f[8],0)*100.0);fix.velocity_valid=true;}emit=true;}else if(strstr(f[0],"GGA")&&n>9){if(f[2][0]&&f[4][0]){double lat=dm(f[2]),lon=dm(f[4]);if(f[3][0]=='S')lat=-lat;if(f[5][0]=='W')lon=-lon;fix.latitude_e7=(int32_t)llround(lat*1e7);fix.longitude_e7=(int32_t)llround(lon*1e7);fix.fix_quality=(uint8_t)atoi(f[6]);fix.satellites=(uint8_t)atoi(f[7]);fix.hdop_centi=(uint16_t)llround(strtod(f[8],0)*100.0);fix.altitude_mm=(int32_t)llround(strtod(f[9],0)*1000.0);fix.position_valid=fix.fix_quality>0;}emit=true;}if(emit){obu_event_t e={.source=OBU_SOURCE_GNSS,.type=OBU_DATA_GNSS_FIX,.sequence=g->seq++,.flags=OBU_EVENT_F_RAW|(fix.position_valid?OBU_EVENT_F_VALID:0),.source_monotonic_us=mono,.validity_ms=1500,.payload_len=sizeof(fix)};memcpy(e.payload,&fix,sizeof(fix));obu_bus_publish(g->c.bus,&e);}}
static void task(void*arg){struct obu_l76k*g=arg;char line[180];size_t p=0;uint8_t b[64];uint32_t err_count=0;for(;;){int n=uart_read_bytes(g->c.uart,b,sizeof(b),pdMS_TO_TICKS(200));if(n<0){if((++err_count%50)==1)ESP_LOGE(TAG,"uart_read_bytes failed on UART%d; backing off",(int)g->c.uart);vTaskDelay(pdMS_TO_TICKS(20));continue;}err_count=0;for(int i=0;i<n;i++){char ch=(char)b[i];if(ch=='\n'){line[p]=0;while(p&&line[p-1]=='\r')line[--p]=0;uint64_t mono=obu_monotonic_us();if(p){pub_raw(g,line,mono);parse_and_pub(g,line,mono);}p=0;}else if(p<sizeof(line)-1)line[p++]=ch;else p=0;}}}
esp_err_t obu_l76k_start(const obu_l76k_config_t*c,obu_l76k_t**out){if(!c||!c->bus||!out)return ESP_ERR_INVALID_ARG;struct obu_l76k*g=calloc(1,sizeof(*g));if(!g)return ESP_ERR_NO_MEM;g->c=*c;uart_config_t u={.baud_rate=c->baud,.data_bits=UART_DATA_8_BITS,.parity=UART_PARITY_DISABLE,.stop_bits=UART_STOP_BITS_1,.flow_ctrl=UART_HW_FLOWCTRL_DISABLE,.source_clk=UART_SCLK_DEFAULT};ESP_ERROR_CHECK(uart_driver_install(c->uart,2048,0,0,NULL,0));ESP_ERROR_CHECK(uart_param_config(c->uart,&u));ESP_ERROR_CHECK(uart_set_pin(c->uart,c->tx_gpio,c->rx_gpio,UART_PIN_NO_CHANGE,UART_PIN_NO_CHANGE));xTaskCreate(task,"l76k",4096,g,10,&g->task);*out=g;return ESP_OK;}
