#include "obu_otm.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "esp_crt_bundle.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_wifi.h"
#include "mqtt_client.h"
#include "nvs_flash.h"
struct obu_otm{bool enabled,wifi_ready,mqtt_ready;char topic[96],status[96];esp_mqtt_client_handle_t mqtt;uint32_t attempted,successful,drops,errors;};static struct obu_otm*g;
static void wifi_evt(void*a,esp_event_base_t base,int32_t id,void*d){(void)a;(void)d;if(!g)return;if(base==WIFI_EVENT&&id==WIFI_EVENT_STA_START)esp_wifi_connect();else if(base==WIFI_EVENT&&id==WIFI_EVENT_STA_DISCONNECTED){g->wifi_ready=false;g->mqtt_ready=false;esp_wifi_connect();}else if(base==IP_EVENT&&id==IP_EVENT_STA_GOT_IP)g->wifi_ready=true;}
static void mqtt_evt(void*arg,esp_event_base_t b,int32_t id,void*data){(void)b;(void)data;struct obu_otm*o=arg;if(id==MQTT_EVENT_CONNECTED){o->mqtt_ready=true;esp_mqtt_client_publish(o->mqtt,o->status,"online",0,0,1);}else if(id==MQTT_EVENT_DISCONNECTED)o->mqtt_ready=false;}
esp_err_t obu_otm_wifi_start(const obu_otm_wifi_config_t*c,obu_otm_t**out){if(!c||!out)return ESP_ERR_INVALID_ARG;struct obu_otm*o=calloc(1,sizeof(*o));if(!o)return ESP_ERR_NO_MEM;o->enabled=c->enabled;if(!c->enabled){*out=o;return ESP_OK;}if(!c->wifi_ssid||!c->wifi_ssid[0]||!c->node_id||!c->node_id[0]){free(o);return ESP_ERR_INVALID_ARG;}snprintf(o->topic,sizeof(o->topic),"its/%s/packet",c->node_id);snprintf(o->status,sizeof(o->status),"its/%s/status",c->node_id);esp_err_t ne=nvs_flash_init();if(ne==ESP_ERR_NVS_NO_FREE_PAGES||ne==ESP_ERR_NVS_NEW_VERSION_FOUND){ESP_ERROR_CHECK(nvs_flash_erase());ne=nvs_flash_init();}ESP_ERROR_CHECK(ne);ESP_ERROR_CHECK(esp_netif_init());esp_err_t ee=esp_event_loop_create_default();if(ee!=ESP_OK&&ee!=ESP_ERR_INVALID_STATE)return ee;esp_netif_create_default_wifi_sta();wifi_init_config_t wi=WIFI_INIT_CONFIG_DEFAULT();ESP_ERROR_CHECK(esp_wifi_init(&wi));wifi_config_t wc={0};strncpy((char*)wc.sta.ssid,c->wifi_ssid,sizeof(wc.sta.ssid)-1);if(c->wifi_password)strncpy((char*)wc.sta.password,c->wifi_password,sizeof(wc.sta.password)-1);ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT,ESP_EVENT_ANY_ID,wifi_evt,NULL));ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT,IP_EVENT_STA_GOT_IP,wifi_evt,NULL));g=o;ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA,&wc));ESP_ERROR_CHECK(esp_wifi_start());esp_mqtt_client_config_t mc={.broker.address.uri=c->broker_uri?c->broker_uri:"mqtts://cits1.opentrafficmap.org:8883",.broker.verification.crt_bundle_attach=esp_crt_bundle_attach,.session.last_will.topic=o->status,.session.last_will.msg="offline",.session.last_will.retain=1,.session.last_will.qos=0};o->mqtt=esp_mqtt_client_init(&mc);if(!o->mqtt)return ESP_FAIL;esp_mqtt_client_register_event(o->mqtt,ESP_EVENT_ANY_ID,mqtt_evt,o);ESP_ERROR_CHECK(esp_mqtt_client_start(o->mqtt));*out=o;return ESP_OK;}
esp_err_t obu_otm_publish_live_frame(obu_otm_t*o,const uint8_t*f,size_t n){if(!o||!f||!n)return ESP_ERR_INVALID_ARG;o->attempted++;if(!o->enabled){o->errors++;return ESP_ERR_NOT_SUPPORTED;}if(!o->mqtt_ready){o->drops++;o->errors++;return ESP_ERR_INVALID_STATE;}int id=esp_mqtt_client_publish(o->mqtt,o->topic,(const char*)f,(int)n,0,0);if(id<0){o->errors++;return ESP_FAIL;}o->successful++;return ESP_OK;}
uint32_t obu_otm_drop_disconnected(const obu_otm_t*o){return o?o->drops:0;}uint32_t obu_otm_publish_errors(const obu_otm_t*o){return o?o->errors:0;}void obu_otm_get_stats(const obu_otm_t*o,obu_otm_stats_t*s){if(!s)return;memset(s,0,sizeof(*s));if(o)*s=(obu_otm_stats_t){.attempted=o->attempted,.successful=o->successful,.failed=o->errors,.dropped_disconnected=o->drops,.connected=o->mqtt_ready};}
