#include "obu_time.h"
#include <string.h>
#include <stdlib.h>
#include <time.h>
#define RTC_ADDR 0x51
static int bcd(uint8_t v){return (v>>4)*10+(v&15);} static uint8_t tobcd(int v){return (uint8_t)(((v/10)<<4)|(v%10));}
static time_t utc_mktime(struct tm *tm){char *old=getenv("TZ");char copy[64]={0};if(old)strncpy(copy,old,sizeof(copy)-1);setenv("TZ","UTC0",1);tzset();time_t t=mktime(tm);if(old)setenv("TZ",copy,1);else unsetenv("TZ");tzset();return t;}
esp_err_t obu_time_init(obu_time_service_t*t,i2c_master_bus_handle_t bus){if(!t||!bus)return ESP_ERR_INVALID_ARG;memset(t,0,sizeof(*t));t->lock=(portMUX_TYPE)portMUX_INITIALIZER_UNLOCKED;i2c_device_config_t c={.dev_addr_length=I2C_ADDR_BIT_LEN_7,.device_address=RTC_ADDR,.scl_speed_hz=100000};esp_err_t e=i2c_master_bus_add_device(bus,&c,&t->rtc);if(e!=ESP_OK)return e;int64_t ns;if(obu_time_read_rtc(t,&ns)==ESP_OK){t->anchor=(obu_time_anchor_t){.utc_ns=ns,.mono_us=obu_monotonic_us(),.quality=OBU_TIME_RTC_HOLDOVER,.valid=true};}return ESP_OK;}
esp_err_t obu_time_read_rtc(obu_time_service_t*t,int64_t*ns){if(!t||!t->rtc||!ns)return ESP_ERR_INVALID_ARG;uint8_t reg=0x02,d[7];esp_err_t e=i2c_master_transmit_receive(t->rtc,&reg,1,d,7,50);if(e!=ESP_OK)return e;if(d[0]&0x80)return ESP_ERR_INVALID_STATE;struct tm x={0};x.tm_sec=bcd(d[0]&0x7f);x.tm_min=bcd(d[1]&0x7f);x.tm_hour=bcd(d[2]&0x3f);x.tm_mday=bcd(d[3]&0x3f);x.tm_mon=bcd(d[5]&0x1f)-1;x.tm_year=100+bcd(d[6]);time_t s=utc_mktime(&x);if(s<0)return ESP_FAIL;*ns=(int64_t)s*1000000000LL;return ESP_OK;}
esp_err_t obu_time_set_rtc(obu_time_service_t*t,int64_t ns){if(!t||!t->rtc)return ESP_ERR_INVALID_ARG;time_t s=(time_t)(ns/1000000000LL);struct tm x;gmtime_r(&s,&x);uint8_t d[8]={0x02,tobcd(x.tm_sec),tobcd(x.tm_min),tobcd(x.tm_hour),tobcd(x.tm_mday),tobcd(x.tm_wday),tobcd(x.tm_mon+1),tobcd(x.tm_year%100)};return i2c_master_transmit(t->rtc,d,sizeof(d),50);}
void obu_time_ingest_pps(obu_time_service_t*t,uint64_t mono){if(!t)return;portENTER_CRITICAL(&t->lock);t->last_pps_us=mono;portEXIT_CRITICAL(&t->lock);}
esp_err_t obu_time_ingest_gnss_utc(obu_time_service_t*t,int64_t ns,uint64_t rx,bool usepps){if(!t)return ESP_ERR_INVALID_ARG;uint64_t pps;portENTER_CRITICAL(&t->lock);pps=t->last_pps_us;portEXIT_CRITICAL(&t->lock);uint64_t mono=rx;obu_time_quality_t q=OBU_TIME_GNSS;if(usepps&&pps&&rx>=pps&&rx-pps<1500000){mono=pps;q=OBU_TIME_GNSS_PPS;ns=(ns/1000000000LL)*1000000000LL;}portENTER_CRITICAL(&t->lock);t->anchor=(obu_time_anchor_t){.utc_ns=ns,.mono_us=mono,.quality=q,.valid=true};portEXIT_CRITICAL(&t->lock);(void)obu_time_set_rtc(t,ns);return ESP_OK;}
bool obu_time_now(obu_time_service_t*t,uint64_t mono,int64_t*ns,obu_time_quality_t*q){if(!t)return false;portENTER_CRITICAL(&t->lock);obu_time_anchor_t a=t->anchor;portEXIT_CRITICAL(&t->lock);if(!a.valid)return false;if(ns)*ns=a.utc_ns+(int64_t)(mono-a.mono_us)*1000LL;if(q)*q=a.quality;return true;}
